name: Dependabot
on:
  push:
    branches:
      - dependabot/go_modules/github.com/gotd/td-*
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-bindings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2.3.4

      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16

      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v2.1.5
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: update-schema-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            update-schema-${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download && go mod tidy

      - name: Generate files
        run: make generate

      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v3.8.2
        with:
          author: GitHub <actions@github.com>
          committer: GitHub <actions@github.com>
          commit-message: 'chore: regenerate bindings'
          branch: feat/update-bindings
          delete-branch: true

          title: Update bindings.
          body: |
            Update td bindings to the latest layer.
          labels: |
            dependencies
