name: e2e

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Run E2E tests
    runs-on: ubuntu-latest
    services:
      vault:
        image: "vault:latest"
        ports:
          - 8200:8200
        env:
          VAULT_DEV_ROOT_TOKEN_ID: testtoken

    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go mod download

      - name: Go generate
        run: |
          go generate ./...

      - name: Run tests
        env:
          TGCONTRIB_VAULT_E2E_RUNNER: local_vault
          VAULT_ADDR: "http://localhost:8200"
          VAULT_TOKEN: "testtoken"
        run: |
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
