name: E2E
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  vault:
    runs-on: ubuntu-latest
    services:
      vault:
        image: "vault:latest"
        ports:
          - 8200:8200
        env:
          VAULT_DEV_ROOT_TOKEN_ID: testtoken
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16

      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: check-mod-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            check-mod-${{ runner.os }}-go-

      - name: Run tests
        env:
          VAULT_ADDR: "http://localhost:8200"
          VAULT_TOKEN: "testtoken"
        run: make e2e_vault_test

      - name: Send coverage
        uses: codecov/codecov-action@v1.3.1
        with:
          file: profile.out

  redis:
    runs-on: ubuntu-latest
    services:
      vault:
        image: "redis:latest"
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16

      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: check-mod-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            check-mod-${{ runner.os }}-go-

      - name: Run tests
        env:
          REDIS_ADDR: "localhost:6379"
        run: make e2e_redis_test

      - name: Send coverage
        uses: codecov/codecov-action@v1.3.1
        with:
          file: profile.out